### ISSUE TITLE
下拉返回时，nav会有微微的弹动，本来就这样？

### ISSUE THREAD

**Issue by liujieyuu** [tujinqiu/KTDropdownMenuView#2]
下拉返回时，nav会有微微的弹动，本来就这样？

**Comment by tujinqiu** [comment]
这是因为动画方法中 usingSpringWithDamping:0.7这个参数小于1会出现震荡效果。用普通的animateWithDuration方法的话就可以去掉震荡效果

**Comment by liujieyuu** [comment]
额，谢谢
