### ISSUE TITLE
关于tableView的top约束的含义

### ISSUE THREAD

**Issue by gq630960023** [tujinqiu/KTDropdownMenuView#6]
我在浏览的代码的时候看到, 关于menuView中tableView的约束为

```
        make.top.equalTo(self.wrapperView.mas_top).offset(-tableCellsHeight - kKTDropdownMenuViewHeaderHeight);
        make.bottom.equalTo(self.wrapperView.mas_bottom).offset(tableCellsHeight + kKTDropdownMenuViewHeaderHeight);
```

其中, top部分的偏移为 :  -tableCellsHeight - kKTDropdownMenuViewHeaderHeight.
请问, 这个偏移量的设定, 是什么意思呢?

**Comment by tujinqiu** [comment]
就是说tableView的上边到wrapperView的上边的距离是-tableCellsHeight - kKTDropdownMenuViewHeaderHeight。这是为了让菜单隐藏时，菜单（高度为tableCellsHeight ）和上面的header（高度为kKTDropdownMenuViewHeaderHeight）处于wrapperView的上面，从而被遮住。

**Comment by gq630960023** [comment]
哦! 所谓的展开, 是一个位移的过程, 对吧?

**Comment by tujinqiu** [comment]
是的

**Comment by gq630960023** [comment]
THX!
